### PR TITLE
Firebase integration - authentication (log in, sign up) and firestore database 

### PR DESCRIPTION
**Pull request by ammaarkhan**

### CODE REVIEW

**Review by oankit — COMMENTED** [review]
Looks great. Just need to get to get access to firebase for appropriate testing of features.

**Review by ribhavsharma — APPROVED** [review]
Great work! Works as expected.

**Review by gabe-matu — APPROVED** [review]
The code is looking good to merge, and is working well.

**Comment by ammaarkhan** [comment]
> Looks great. Only thing is for the sign up, when verifying the password, the user should be notified if the password does not meet the required criteria (example: password needs to be 6 figures)

ok boss will do inshallah

**Pull request merged**
